### PR TITLE
Add kinetic to CI

### PR DESCRIPTION
**Pull request by evenator**

### CODE REVIEW

**Comment by 130s** [comment]
`industrial_ci` isn't tested for Ubuntu 16.04 simply because Travis CI hasn't yet planned to support it. https://github.com/ros-industrial/industrial_ci/issues/51

How about moving `kinetic` to `allow_failures` section for now, to let your jobs pass?

**Comment by pjreed** [comment]
@evenator  It seems like the build is failing due to being unable to find swri_transform_util.  Has that been released into kinetic?

**Comment by evenator** [comment]
@pjreed Nope. That's part of marti_common, which is blocked on a bunch of opencv issues that I haven't looked at yet, IIRC.

**Comment by evenator** [comment]
Closing this in favor of creating a separate branch for kinetic devel.

**Pull request closed without merging**
