### PR TITLE
Image plugin: "percent" should refer to original image size

### PR DESCRIPTION
**Pull request by facontidavide**
Change proposed in #542 

I also changed few attributes to types QPointF and QSizeF, that, I know, might be an opinionated decision.

### CODE REVIEW

**Comment by malban** [comment]
I like this, but can we keep the original behavior as an option.  It is sometimes useful to have the image scale with the window.  The options could be: Pixel, Percent, Percent of Canvas or something.

**Comment by facontidavide** [comment]
It make sense, but honestly I am prioritizing other improvements that are more relevant for may project, therefore I will not be able to focus on enhancing this PR as you suggest until the second half of January.

**Comment by malban** [comment]
No worries.

**Comment by facontidavide** [comment]
I will temporarily close this PR, to focus better on the others PR still ones

**Pull request closed without merging**
