### PR TITLE
Glew warning fixed

### PR DESCRIPTION
**Pull request by facontidavide**
Hi,

this PR should reduce the number of warnings related to glew.h

Cheers

### CODE REVIEW

**Comment by evenator** [comment]
I don't have a kinetic environment at work, but if I get a chance, I can test this out at home.

**Comment by danthony06** [comment]
The PR worked in my Kinetic workspace.

**Comment by facontidavide** [comment]
Travis CI is happy too :)

**Comment by evenator** [comment]
Thank you for improving mapviz!

**Comment by evenator** [comment]
@pjreed Should I backport this to Indigo?

**Comment by pjreed** [comment]
Give it a try; if it backports cleanly and everything runs, I'd say to go ahead and do it, but don't worry about it if it breaks things, since those warnings don't exist on Indigo.

**Pull request merged**
