### PR TITLE
Change for loop to while loop.

### PR DESCRIPTION
**Pull request by mdgrogan**
Change for loop to a while loop so that we don't skip items and overshoot the end of the container when erasing.

### CODE REVIEW

**Comment by matt-attack** [comment]
I'm not sure that I see a difference in what is executed here. Does this fix a crash?

**Comment by danthony06** [comment]
It looks like with the change it's possible to dereference an invalid
iterator.

**Comment by mdgrogan** [comment]
Where does that occur?

**Comment by danthony06** [comment]
Sorry about that, I misread the code on my phone and thought the continue
statements had been removed. I'm still not sure what problem this change is
addressing.

**Comment by mdgrogan** [comment]
Ah, no worries. The erase function returns the next iterator and at the end of the for loop, that iterator will be incremented again. So it potentially skips items and increments the iterator past end.

**Pull request merged**
